### ISSUE TITLE
Parse updates from replication log into JSON values

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric-next#100]
When playing with the Getting Started guide in the README I noticed that after an update to the row with id 2, the 2 becomes "2". So probably something off with how we're parsing the replication log?

<img width="226" alt="Screenshot 2024-07-17 at 3 25 42 PM" src="https://github.com/user-attachments/assets/a22d86d2-c7d5-426c-b64a-111a6e149a28">

## Checklist
- [ ] update TODO example app to stop its special casing of string boolean values

**Comment by thruflo** [comment]
I'm not sure about the half and half solution.

Everything comes out of Postgres as a string, with the column type information provided before you get the serialised values. That strikes me as a battle tested, consistent pattern that pushes the responsibility onto the client.

Now, if we want our materialised Shape client to be schema aware and deserialise an integer string into an integer so be it. But I would argue the shape log messages should have values in a consistent serialised form.

**Comment by balegas** [comment]
the server could be plain dumb and just pass strings and the associated type information in an attribute: ```_schema: {col1: int}``` we have that information.  We could build the json at byte-level. that would also help with server serialization costs. I like that.

Some nuances that pg-proto types might not match DDL types, but I believe Ilia will know all about this.

**Comment by KyleAMathews** [comment]
>shape log messages should have values in a consistent serialised form

The problem we're trying to solve is we're *not* consistent. This issue isn't about breaking consistency — it's that data starts consistently as numbers and booleans and strings and then somehow, mysteriously they all becomes a string. We're already in the half and half solution and need to get out of it.

So to become consistent, either we (de)serialize all the initial query data or b) we keep converting postgres data formats that match JSON data types to JSON.

It's far simpler to do this on the server as a) it already has the schema info and b) every language in the world has a JSON parser to native data types. It'd be slower and far more error prone if people have to come up with a mapping themselves for types and then do a JSON parse, iterate over data, and then us the data.

The percentage of PostgreSQL data types that don't directly map to JSON is relatively small and people that use the other types are already used to figuring out how to handle them on the client e.g. PostGIS data.

It'll be very surprising and annoying to people if we don't do straightforward conversions to JSON data types for them e.g. this blog post:

https://medium.com/developer-rants/postgresql-node-js-and-those-damn-floating-point-values-d3a39b432b03

> If you’re using connect-pg-simple for your Node.js database needs, you might have experienced a slight inconvenience: floating point numbers are returned to Node.js as strings, not numeric values. Otherwise, connect-pg-simple is lovely, but this is hecking annoying!

**Comment by balegas** [comment]
Decision: map pg-protocol to json, which is what users expect.

**Comment by thruflo** [comment]
Yup, we serialise the basic JSON types that we can (`string`, `integer`, `float`, `boolean`, `array`, `object`) and we leave other types in their binary serialisation. This means basic types behave as expected out of the box, but then more esoteric types are the responsibility of the client or app to serialise out of binary.

**Comment by KyleAMathews** [comment]
The Northwind schema is a good one for testing lots of data types https://github.com/mrin9/northwind

**Comment by KyleAMathews** [comment]
Ok, after a long discussion as a team, we decided to try doing serialization in the client. The reasons are:
1. JSON serialization can be lossy in some instances e.g. floats
2. JSON types translate very well of course to JavaScript but there'll be clients written in other languages so delaying serialization until data reaches the client means we can optimize serialization for each environment.
3. we want to add support for custom parsing anyways so might as well bake that in from the start.

So the proposed change we'll want to try is that the server sends the Shape schema somehow (perhaps just the first message in the log) and then the client uses that schema info to parse the incoming data. Eventually we'll allow users to pass in their own parse functions for specific data but we won't do that initially.

We'll want to benchmark the parse performance of this approach vs. just doing a native JSON.parse in the browser. If there's a sharp regression, we'll want to keep the log then in native JSON for supported types.
