### ISSUE TITLE
Opting table into replication

### ISSUE THREAD

**Issue by thruflo** [electric-sql/electric-next#154]
I'm raising this now because I'd like to know what the impact on PG storage amplification having all tables (with replica full?) on the replication stream.

If heavy, we maybe want to prioritise opting table in. This could be via:

a) instructions for the user to DIY
b) a database function
c) an endpoint `POST /v1/electrify/:table` `POST /v1/unelectrify/:table`

**Comment by icehaunter** [comment]
WDYM "opting it in"? Current `main` doesn't add a table to a publication (and thus replication) until a first shape call already. I though that "locking down" tables (i.e. not make them subscribe-able at all) is a job for a layer above that would provide authorization of some kind (or for a beta/full release if rolled into the product)

**Comment by thruflo** [comment]
Right, that's great, I was out of date with the current implementation.
