### ISSUE TITLE
Add schema information to the response in the headers

### ISSUE THREAD

**Issue by icehaunter** [electric-sql/electric-next#163]
Continuing on from #100, server should provide schema information so that the client can parse string values into better representations

**Comment by KyleAMathews** [comment]
This is nice as dev tooling can do a `HEAD` request to get info about a shape.

**Comment by KyleAMathews** [comment]
ah yeah — something to keep at the back of our heads for future work!

**Comment by icehaunter** [comment]
@KyleAMathews supporting a `HEAD` also allows for cleaner `ShapeStream` initialization, where a `HEAD` request gets us early 400 validation on table existence & where clauses, doesn't it?

**Comment by KyleAMathews** [comment]
Normally validation like that is just done as part of the `GET` request as then, assuming validation passes, the server can immediately respond with the body vs. waiting for another request.

**Comment by icehaunter** [comment]
Closed via #168
