### ISSUE TITLE
Support qualified tablenames.

### ISSUE THREAD

**Issue by thruflo** [electric-sql/electric-next#173]
Next has regressed to only supporting a table name, instead of a schema.tablename. This forces all syncable tables to be in the public schema.

**Comment by icehaunter** [comment]
Can you show the regression? Our frontend tests are requesting shapes like this:
```
http://localhost:3000/v1/shape/electric_test.issues%20for%20181577045_0_0?offset=-1
```
and are getting correct tables from `electric_test` schema (`main` is green). What we're lacking is more complicated parsing of these components (i.e. we don't respect table names with `.` and don't allow escaping table names) - did you maybe encounter that?

**Comment by thruflo** [comment]
Right, I hadn't tried it. I was looking at the code and docs using the variable name `root_table` as a string and assuming it's a tablename, as per https://next.electric-sql.com/openapi.html#/paths/~1v1~1shape~1%7Broot_table%7D/get

If we do support `schema.table` then I can document that.

**Comment by icehaunter** [comment]
We do, although I think we may want to support `table?schema=schema` instead? WDYT?

**Comment by icehaunter** [comment]
we already internally parse it in Elixir, just highlighting that current parser is naive and always assumes a single dot in the string, failing otherwise. `.` can be unambiguous if we settle on an escape pattern. Splitting only on first dot also seems like a very sane default

**Comment by thruflo** [comment]
Closing in favour of https://github.com/electric-sql/electric-next/issues/185
