### ISSUE TITLE
Verify and document TOAST values behaviour

### ISSUE THREAD

**Issue by balegas** [electric-sql/electric-next#61]
TOASTed column values are not sent down logical replication stream when they haven't changed in an update. With Electric, this was a problem because it would fail schema validation on the client. In Electric-next this is less of a problem because clients are schemaless (for now).

We need to check and document how the client behaves: when an update arrives for a row, is it the value of the TOASTed column being replaced with a null value? Check manually and create an integration test in the client capturing the expected behaviour.

**Comment by KyleAMathews** [comment]
We have two options — *always* pass the entire row each time or just send a patch — if we decide to send patches, then a TOAST value not being in the message is fine. If we send the entire row each time we'll need to fetch the TOAST value each time.

**Comment by balegas** [comment]
Analyse potential solution assuming we don't have any extra info about schema in the client

**Comment by KyleAMathews** [comment]
Update: we're still working out exactly how we want to get TOAST values into the log on the backend.

One change we can implement immediately however is moving to a patch update model. Currently everything assumes that each message contains the entire value of each row. This is not ideal as it means updates to shapes with large rows will be pretty heavy to send to clients. It's much more efficient and fast to send just the update. So we'll want to update the `Shape` TS class to merge in updates as well as the Redis & Bash clients (or perhaps just delete the bash client as it's more for fun than serious — bash is annoying to write).

**Comment by alco** [comment]
According to Postgres docs on [REPLICA IDENTITY](https://www.postgresql.org/docs/current/sql-altertable.html#SQL-ALTERTABLE-REPLICA-IDENTITY),
> This form changes the information which is written to the write-ahead log to identify rows which are updated or deleted. In most cases, the old value of each column is only logged if it differs from the new value; however, if the old value is stored externally, it is always logged regardless of whether it changed.

Several observations from surveying Postgres' source code:
- when building logical messages for the replication connection, Postgres reads tuples from the WAL and does next to no processing on them
- in the implementation of `pgoutput_row_filter()` function that carries out the evaluation of [row filters](https://www.postgresql.org/docs/current/logical-replication-row-filter.html) for logical messages, there's this [code comment](https://github.com/postgres/postgres/blob/d3cc5ffe81f64c6418ba9b18a9db32392f8027e6/src/backend/replication/pgoutput/pgoutput.c#L1316-L1321):

      /*
       * Unchanged toasted replica identity columns are only logged in the
       * old tuple. Copy this over to the new tuple. The changed (or WAL
       * Logged) toast values are always assembled in memory and set as
       * VARTAG_INDIRECT. See ReorderBufferToastReplace.
       */

- The `ExtractReplicaIdentity()` function has this [code comment](https://github.com/postgres/postgres/blob/d3cc5ffe81f64c6418ba9b18a9db32392f8027e6/src/backend/access/heap/heapam.c#L8680-L8683):

      /*
       * When logging the entire old tuple, it very well could contain
       * toasted columns. If so, force them to be inlined.
       */

   where "logging" refers to writing the tuple to the WAL.

**Comment by thruflo** [comment]
Brilliant — so a toasted value will always be present in the old record when using replica identity full. No need to query back or maintain a toast cache.

**Comment by balegas** [comment]
Glad someone actually read the docs! Let’s try it out
