### ISSUE TITLE
All examples should be easy to run

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric-next#79]
Probably a script `npm run backend-services` which runs the Docker instances & runs the db migrations & then a `npm run dev` for running the js dev server.

**Comment by thruflo** [comment]
I know this has been closed but just to feed in:

We've lost so much time to local dev/cli tooling with docker. It's just a fucking nightmare, with variation in local setups and skills. I would really strongly steer on the side of just use the standard tools yourself vs us putting magic in npm commands.
